In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
path = "./tweets-data"
datas = os.listdir(path)
datas1 = [i for i in datas if "Kabur" in i]
# datas2 = [i for i in datas if "Kabur" not in i]
datas1

['#KaburAjaDulu_lang-id_since-2025-1-1_until-2025-2-1.csv',
 '#KaburAjaDulu_lang-id_since-2025-2-1_until-2025-3-1.csv',
 '#KaburAjaDulu_lang-id_since-2025-2-1_until-2025-3-1.old.csv',
 '#KaburAjaDulu_lang-id_since-2025-3-1_until-2025-4-1.csv',
 '#KaburAjaDulu_lang-id_since-2025-4-1_until-2025-5-1.csv',
 '#KaburAjaDulu_lang-id_since-2025-5-1_until-2025-5-30.csv',
 'Kabur_Aja_Dulu_lang-id_since-2025-1-1_until-2025-2-1.csv',
 'Kabur_Aja_Dulu_lang-id_since-2025-2-1_until-2025-3-1.csv',
 'Kabur_Aja_Dulu_lang-id_since-2025-3-1_until-2025-4-1.csv',
 'Kabur_Aja_Dulu_lang-id_since-2025-4-1_until-2025-5-1.csv',
 'Kabur_Aja_Dulu_lang-id_since-2025-5-1_until-2025-5-30.csv']

In [4]:
dfs = {f"df{i}": pd.read_csv(f"{path}/{datas1[i]}") for i in range(len(datas1))}
df1 = pd.concat(list(dfs.values()), ignore_index=True)
df1['Media'] = df1.shape[0]*["X"]
df1

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,Media
0,1.885470e+18,Fri Jan 31 23:46:36 +0000 2025,0,gua udh siap untuk #KaburAjaDulu dr Indo tapi ...,1.885470e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/188547479826617...,8.844280e+17,NaN,X
1,1.885340e+18,Fri Jan 31 23:42:59 +0000 2025,1,@primawansatrio Ini banget!!! Rata2 kita yg pe...,1.885470e+18,NaN,primawansatrio,in,NaN,0,0,0,https://x.com/undefined/status/188547388785047...,1.224490e+18,NaN,X
2,1.885470e+18,Fri Jan 31 23:42:04 +0000 2025,0,#KaburAjaDulu harusnya sih #KaburAjaSelamanya ...,1.885470e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/188547365499957...,1.230380e+18,NaN,X
3,1.885460e+18,Fri Jan 31 22:44:21 +0000 2025,1,Coyy selisih 11 suara di Bundestag tolak atura...,1.885460e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/188545912894586...,1.714545e+08,NaN,X
4,1.885130e+18,Fri Jan 31 22:29:09 +0000 2025,0,@investorgabut Atau orang yg sejarah hidupnya ...,1.885460e+18,NaN,CihuyMustajab,in,NaN,0,0,0,https://x.com/undefined/status/188545530582554...,1.130690e+18,NaN,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4441,1.925953e+18,Sat May 24 17:12:54 +0000 2025,0,@quirkymeow Dampak kabur aja dulu is real,1.926326e+18,NaN,quirkymeow,in,NaN,0,0,0,https://x.com/undefined/status/192632554895283...,3.976830e+08,NaN,X
4442,1.926319e+18,Sat May 24 16:45:05 +0000 2025,0,Bisa ga dalam 5 tahun kabur aja dulu gitu,1.926319e+18,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/192631854826929...,1.145734e+18,NaN,X
4443,1.913615e+18,Sat May 24 16:33:36 +0000 2025,9,@dearestjeffrey sedih banget Tere kabur keruma...,1.926316e+18,NaN,dearestjeffrey,in,NaN,0,0,0,https://x.com/undefined/status/192631565854072...,1.380436e+18,NaN,X
4444,1.926298e+18,Sat May 24 15:56:45 +0000 2025,2,@typingcntik @njimarkloey intinya kamu udah me...,1.926306e+18,NaN,usedbysuns,in,NaN,0,0,0,https://x.com/undefined/status/192630638416279...,1.692461e+18,NaN,X
4445,1.926302e+18,Sat May 24 15:53:08 +0000 2025,11,@jstwillians Kalo saya ada di situ di situasi ...,1.926305e+18,NaN,jstwillians,in,NaN,0,0,0,https://x.com/undefined/status/192630547288732...,1.515872e+18,NaN,X

In [10]:
df1[df1['user_id_str'] == 3711470718]['tweet_url'].iloc[0]

'https://x.com/undefined/status/1881534778828378600'

In [42]:
print(f"jumlah data duplikat sebelum dihapus: {df1.duplicated().sum()}")
df1 = df1.drop_duplicates()
print(f"jumlah data duplikat setelah dihapus: {df1.duplicated().sum()}")

jumlah data duplikat sebelum dihapus: 107
jumlah data duplikat setelah dihapus: 0

In [43]:
df1 = df1.rename(columns={'favorite_count': 'like_count'})
df1 = df1[[ 'created_at', 'user_id_str', 'full_text', 'like_count', 'quote_count', 'reply_count', 'retweet_count', 'tweet_url', 'Media' 
        # 'id_str','username',
        ]]
df1.columns = ['created_at', 'username/id_user', 'full_text', 'like_count', 'quote_count', 'reply_count', 'retweet_count', 'tweet_url', 'Media']
df1['username/id_user'] = df1['username/id_user'].astype(int)
df1

,created_at,username/id_user,full_text,like_count,quote_count,reply_count,retweet_count,tweet_url,Media
0,Fri Jan 31 23:46:36 +0000 2025,884428000000000000,gua udh siap untuk #KaburAjaDulu dr Indo tapi ...,0,0,0,0,https://x.com/undefined/status/188547479826617...,X
1,Fri Jan 31 23:42:59 +0000 2025,1224490000000000000,@primawansatrio Ini banget!!! Rata2 kita yg pe...,1,0,0,0,https://x.com/undefined/status/188547388785047...,X
2,Fri Jan 31 23:42:04 +0000 2025,1230380000000000000,#KaburAjaDulu harusnya sih #KaburAjaSelamanya ...,0,0,0,0,https://x.com/undefined/status/188547365499957...,X
3,Fri Jan 31 22:44:21 +0000 2025,171454468,Coyy selisih 11 suara di Bundestag tolak atura...,1,0,0,0,https://x.com/undefined/status/188545912894586...,X
4,Fri Jan 31 22:29:09 +0000 2025,1130690000000000000,@investorgabut Atau orang yg sejarah hidupnya ...,0,0,0,0,https://x.com/undefined/status/188545530582554...,X
...,...,...,...,...,...,...,...,...,...
4441,Sat May 24 17:12:54 +0000 2025,397683025,@quirkymeow Dampak kabur aja dulu is real,0,0,0,0,https://x.com/undefined/status/192632554895283...,X
4442,Sat May 24 16:45:05 +0000 2025,1145734451428618240,Bisa ga dalam 5 tahun kabur aja dulu gitu,0,0,0,0,https://x.com/undefined/status/192631854826929...,X
4443,Sat May 24 16:33:36 +0000 2025,1380436173777035264,@dearestjeffrey sedih banget Tere kabur keruma...,9,0,0,0,https://x.com/undefined/status/192631565854072...,X
4444,Sat May 24 15:56:45 +0000 2025,1692460959540064256,@typingcntik @njimarkloey intinya kamu udah me...,2,0,0,0,https://x.com/undefined/status/192630638416279...,X
4445,Sat May 24 15:53:08 +0000 2025,1515872148891762688,@jstwillians Kalo saya ada di situ di situasi ...,11,0,0,0,https://x.com/undefined/status/192630547288732...,X

In [44]:
df2 = pd.read_csv(f"{path}/AMS scraping yt.csv")
df2['quote_count'] = df2.shape[0]*[0]
df2['reply_count'] = df2.shape[0]*[0]
df2['retweet_count'] = df2.shape[0]*[0]
df2['tweet_url'] = df2.shape[0]*[np.nan]
df2['Media'] = df2.shape[0]*["YouTube"]
df2

,publishedAt,authorDisplayName,textDisplay,likeCount,quote_count,reply_count,retweet_count,tweet_url,Media
0,2025-02-14T05:31:06Z,@BBCNewsIndonesia,Simak artikel selengkapnya di tautan ini: <a h...,105,0,0,0,NaN,YouTube
1,2025-02-14T07:21:49Z,@sayfolman7752,Inilah 12 sifat-dasar manusia Indonesia menuru...,1,0,0,0,NaN,YouTube
2,2025-02-14T10:31:38Z,@AmranSaputra-q3r,"Mereka itu tidk penting bagi negara, sialakan ...",1,0,0,0,NaN,YouTube
3,2025-02-14T11:18:47Z,@MamakSaja-zv9wc,Indonesia tdk dlm perang.<br>Kebutuhan hidup a...,25,0,0,0,NaN,YouTube
4,2025-02-14T12:33:37Z,@bantar6348,"Mau jadi apapun, dimanapun, rasa akan tetap sa...",13,0,0,0,NaN,YouTube
...,...,...,...,...,...,...,...,...,...
4753,2025-02-16T08:07:23Z,@syukrimaulana623,gini kalau hasil curang,0,0,0,0,NaN,YouTube
4754,2025-02-16T08:06:14Z,@CokiKamaruZaman,"Songong luh, ys bagus si kalo manusia model lu...",0,0,0,0,NaN,YouTube
4755,2025-02-16T08:04:41Z,@ArdiBass,Untuk menanam jd jati diri nasionalis menjadi ...,0,0,0,0,NaN,YouTube
4756,2025-02-16T08:04:21Z,@AgusHarson,"Banggakan negeri sendiri NKRI, dgn meraih pres...",0,0,0,0,NaN,YouTube
4757,2025-02-16T08:03:36Z,@YuniAristianti-wl7de,Seenak2nya d negri orng lbh enak negri sndri ❤...,0,0,0,0,NaN,YouTube

In [45]:
df2.columns = ['created_at', 'username/id_user', 'full_text', 'like_count', 'quote_count', 'reply_count', 'retweet_count', 'tweet_url', 'Media']
df2

,created_at,username/id_user,full_text,like_count,quote_count,reply_count,retweet_count,tweet_url,Media
0,2025-02-14T05:31:06Z,@BBCNewsIndonesia,Simak artikel selengkapnya di tautan ini: <a h...,105,0,0,0,NaN,YouTube
1,2025-02-14T07:21:49Z,@sayfolman7752,Inilah 12 sifat-dasar manusia Indonesia menuru...,1,0,0,0,NaN,YouTube
2,2025-02-14T10:31:38Z,@AmranSaputra-q3r,"Mereka itu tidk penting bagi negara, sialakan ...",1,0,0,0,NaN,YouTube
3,2025-02-14T11:18:47Z,@MamakSaja-zv9wc,Indonesia tdk dlm perang.<br>Kebutuhan hidup a...,25,0,0,0,NaN,YouTube
4,2025-02-14T12:33:37Z,@bantar6348,"Mau jadi apapun, dimanapun, rasa akan tetap sa...",13,0,0,0,NaN,YouTube
...,...,...,...,...,...,...,...,...,...
4753,2025-02-16T08:07:23Z,@syukrimaulana623,gini kalau hasil curang,0,0,0,0,NaN,YouTube
4754,2025-02-16T08:06:14Z,@CokiKamaruZaman,"Songong luh, ys bagus si kalo manusia model lu...",0,0,0,0,NaN,YouTube
4755,2025-02-16T08:04:41Z,@ArdiBass,Untuk menanam jd jati diri nasionalis menjadi ...,0,0,0,0,NaN,YouTube
4756,2025-02-16T08:04:21Z,@AgusHarson,"Banggakan negeri sendiri NKRI, dgn meraih pres...",0,0,0,0,NaN,YouTube
4757,2025-02-16T08:03:36Z,@YuniAristianti-wl7de,Seenak2nya d negri orng lbh enak negri sndri ❤...,0,0,0,0,NaN,YouTube

In [46]:
dff = pd.concat([df1, df2], ignore_index=True)
dff

,created_at,username/id_user,full_text,like_count,quote_count,reply_count,retweet_count,tweet_url,Media
0,Fri Jan 31 23:46:36 +0000 2025,884428000000000000,gua udh siap untuk #KaburAjaDulu dr Indo tapi ...,0,0,0,0,https://x.com/undefined/status/188547479826617...,X
1,Fri Jan 31 23:42:59 +0000 2025,1224490000000000000,@primawansatrio Ini banget!!! Rata2 kita yg pe...,1,0,0,0,https://x.com/undefined/status/188547388785047...,X
2,Fri Jan 31 23:42:04 +0000 2025,1230380000000000000,#KaburAjaDulu harusnya sih #KaburAjaSelamanya ...,0,0,0,0,https://x.com/undefined/status/188547365499957...,X
3,Fri Jan 31 22:44:21 +0000 2025,171454468,Coyy selisih 11 suara di Bundestag tolak atura...,1,0,0,0,https://x.com/undefined/status/188545912894586...,X
4,Fri Jan 31 22:29:09 +0000 2025,1130690000000000000,@investorgabut Atau orang yg sejarah hidupnya ...,0,0,0,0,https://x.com/undefined/status/188545530582554...,X
...,...,...,...,...,...,...,...,...,...
9092,2025-02-16T08:07:23Z,@syukrimaulana623,gini kalau hasil curang,0,0,0,0,NaN,YouTube
9093,2025-02-16T08:06:14Z,@CokiKamaruZaman,"Songong luh, ys bagus si kalo manusia model lu...",0,0,0,0,NaN,YouTube
9094,2025-02-16T08:04:41Z,@ArdiBass,Untuk menanam jd jati diri nasionalis menjadi ...,0,0,0,0,NaN,YouTube
9095,2025-02-16T08:04:21Z,@AgusHarson,"Banggakan negeri sendiri NKRI, dgn meraih pres...",0,0,0,0,NaN,YouTube
9096,2025-02-16T08:03:36Z,@YuniAristianti-wl7de,Seenak2nya d negri orng lbh enak negri sndri ❤...,0,0,0,0,NaN,YouTube

In [47]:
dff.to_csv(f"{path}/data_UTS_fix.csv", index=False)

In [48]:
dff['username/id_user'].value_counts()

username/id_user
398798880                15
1859524569658425344      12
1667310850477293568      12
1557693391               11
1356061304               10
                         ..
@syukrimaulana623         1
@CokiKamaruZaman          1
@ArdiBass                 1
@AgusHarson               1
@YuniAristianti-wl7de     1
Name: count, Length: 8134, dtype: int64